CREATE TABLE IF NOT EXISTS student(
	student_ID SERIAL PRIMARY KEY,
	name VARCHAR(20),
	major VARCHAR(20)
);
	
DROP TABLE student

CREATE TABLE IF NOT EXISTS artists(
	id SERIAL PRIMARY KEY,
	name VARCHAR
);

DROP TABLE artists

SELECT *
FROM artists; 
